### ISSUE TITLE
Tutorial issue

### ISSUE THREAD

**Issue by EnricoBeltramo** [chromaui/learnstorybook.com#535] opened 2021-10-03 11:55 UTC
The tutorial,
 at step:
https://storybook.js.org/tutorials/intro-to-storybook/react/en/composite-component/

at running yarn test, 
show testing error.
I don't understand where should be the error, there is a way to have a more readable log?

yarn run v1.22.10
$ react-scripts test
 PASS  src/components/TaskList.test.js
(node:23344) DeprecationWarning: \`storyFn\` is deprecated and will be removed in Storybook 7.0.

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-storyfn
(Use `node --trace-deprecation ...` to show where the warning was created)
 FAIL  src/components/storybook.test.js
  ● Storyshots › TaskList › With Pinned Tasks

    expect(received).toMatchSnapshot()

    Snapshot name: `Storyshots TaskList With Pinned Tasks 1`

    - Snapshot  - 8
    + Received  + 8

    @@ -7,11 +7,11 @@
      >
        <div
          className="list-items"
        >
          <div
    -       className="list-item TASK_INBOX"
    +       className="list-item TASK_PINNED"
          >
            <label
              className="checkbox"
            >
              <input
    @@ -30,11 +30,11 @@
            >
              <input
                placeholder="Input title"
                readOnly={true}
                type="text"
    -           value="Task 1"
    +           value="Task 6 (pinned)"
              />
            </div>
            <div
              className="actions"
              onClick={[Function]}
    @@ -70,11 +70,11 @@
            >
              <input
                placeholder="Input title"
                readOnly={true}
                type="text"
    -           value="Task 2"
    +           value="Task 1"
              />
            </div>
            <div
              className="actions"
              onClick={[Function]}
    @@ -110,11 +110,11 @@
            >
              <input
                placeholder="Input title"
                readOnly={true}
                type="text"
    -           value="Task 3"
    +           value="Task 2"
              />
            </div>
            <div
              className="actions"
              onClick={[Function]}
    @@ -150,11 +150,11 @@
            >
              <input
                placeholder="Input title"
                readOnly={true}
                type="text"
    -           value="Task 4"
    +           value="Task 3"
              />
            </div>
            <div
              className="actions"
              onClick={[Function]}
    @@ -190,11 +190,11 @@
            >
              <input
                placeholder="Input title"
                readOnly={true}
                type="text"
    -           value="Task 5"
    +           value="Task 4"
              />
            </div>
            <div
              className="actions"
              onClick={[Function]}
    @@ -207,11 +207,11 @@
                />
              </a>
            </div>
          </div>
          <div
    -       className="list-item TASK_PINNED"
    +       className="list-item TASK_INBOX"
          >
            <label
              className="checkbox"
            >
              <input
    @@ -230,11 +230,11 @@
            >
              <input
                placeholder="Input title"
                readOnly={true}
                type="text"
    -           value="Task 6 (pinned)"
    +           value="Task 5"
              />
            </div>
            <div
              className="actions"
              onClick={[Function]}

      at match (node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:25:32)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:34:16
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:47:20)

  ● Storyshots › TaskList › Loading

    expect(received).toMatchSnapshot()

    Snapshot name: `Storyshots TaskList Loading 1`

    - Snapshot  -   1
    + Received  + 132

    @@ -6,8 +6,139 @@
        }
      >
        <div
          className="list-items"
        >
    -     loading
    +     <div
    +       className="loading-item"
    +     >
    +       <span
    +         className="glow-checkbox"
    +       />
    +       <span
    +         className="glow-text"
    +       >
    +         <span>
    +           Loading
    +         </span>
    +
    +         <span>
    +           cool
    +         </span>
    +
    +         <span>
    +           state
    +         </span>
    +       </span>
    +     </div>
    +     <div
    +       className="loading-item"
    +     >
    +       <span
    +         className="glow-checkbox"
    +       />
    +       <span
    +         className="glow-text"
    +       >
    +         <span>
    +           Loading
    +         </span>
    +
    +         <span>
    +           cool
    +         </span>
    +
    +         <span>
    +           state
    +         </span>
    +       </span>
    +     </div>
    +     <div
    +       className="loading-item"
    +     >
    +       <span
    +         className="glow-checkbox"
    +       />
    +       <span
    +         className="glow-text"
    +       >
    +         <span>
    +           Loading
    +         </span>
    +
    +         <span>
    +           cool
    +         </span>
    +
    +         <span>
    +           state
    +         </span>
    +       </span>
    +     </div>
    +     <div
    +       className="loading-item"
    +     >
    +       <span
    +         className="glow-checkbox"
    +       />
    +       <span
    +         className="glow-text"
    +       >
    +         <span>
    +           Loading
    +         </span>
    +
    +         <span>
    +           cool
    +         </span>
    +
    +         <span>
    +           state
    +         </span>
    +       </span>
    +     </div>
    +     <div
    +       className="loading-item"
    +     >
    +       <span
    +         className="glow-checkbox"
    +       />
    +       <span
    +         className="glow-text"
    +       >
    +         <span>
    +           Loading
    +         </span>
    +
    +         <span>
    +           cool
    +         </span>
    +
    +         <span>
    +           state
    +         </span>
    +       </span>
    +     </div>
    +     <div
    +       className="loading-item"
    +     >
    +       <span
    +         className="glow-checkbox"
    +       />
    +       <span
    +         className="glow-text"
    +       >
    +         <span>
    +           Loading
    +         </span>
    +
    +         <span>
    +           cool
    +         </span>
    +
    +         <span>
    +           state
    +         </span>
    +       </span>
    +     </div>
        </div>
      </div>

      at match (node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:25:32)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:34:16
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:47:20)

  ● Storyshots › TaskList › Empty

    expect(received).toMatchSnapshot()

    Snapshot name: `Storyshots TaskList Empty 1`

    - Snapshot  -  1
    + Received  + 17

    @@ -6,8 +6,24 @@
        }
      >
        <div
          className="list-items"
        >
    -     empty
    +     <div
    +       className="wrapper-message"
    +     >
    +       <span
    +         className="icon-check"
    +       />
    +       <div
    +         className="title-message"
    +       >
    +         You have no tasks
    +       </div>
    +       <div
    +         className="subtitle-message"
    +       >
    +         Sit back and relax
    +       </div>
    +     </div>
        </div>
      </div>

      at match (node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:25:32)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:34:16
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:47:20)

 › 3 snapshots failed.
Snapshot Summary
 › 3 snapshots failed from 1 test suite. Inspect your code changes or press `u` to update them.

Test Suites: 1 failed, 1 passed, 2 total
Tests:       3 failed, 5 passed, 8 total
Snapshots:   3 failed, 4 passed, 7 total
Time:        4.645 s
Ran all test suites related to changed files.

**Comment by jonniebigodes** [comment] 2021-10-08 21:47
@EnricoBeltramo thanks for taking the time and reaching out to us with your issue and sorry for the delayed response, but I was otherwise engaged in other aspects of the documentation. I followed up the tutorial trying to replicate your issue and it seems that something is off, sorry but I wasn't able to reproduce it. Looking at your description it seems that something is happening with the snapshot testing. I would like to ask you what happens if you press the `u` key and update the snapshots, then re-run the `test` script, will the same message appear? To give you a bit of context o this, we're aware that the logging isn't quite the best with the `storyshots` addon and it can be quite verbose and diverting you from the key point, this is due to the fact the addon is deeply tied to Jest and uses some of its logging features. The good news is that we're making some improvements on the testing front and hopefully provide you with a better solution in the near future.

Let me know and we'll take from there and coordinate on this to get a resolution to your issue, or continue to work on it until we find a suitable solution.

Have a great weekend!

Stay safe

**Comment by jonniebigodes** [comment] 2021-11-10 23:29
@EnricoBeltramo closing this down as I'm unable to reproduce it. I've followed up the tutorial in both a MacOs machine, a Windows 11 machine, and also with a WSL Ubuntu machine. If the problem still persists for you! Please let me know and I'll gladly re-open this issue and follow up with you!

Have a great week!

Stay safe

**Closed by jonniebigodes** 2021-11-10 23:29 UTC
