### ISSUE TITLE
Final code for the 'data' chapter doesn't work

### ISSUE THREAD

**Issue by jalovatt** [chromaui/learnstorybook.com#78] opened 2019-01-30 19:41 UTC
Lovely tutorial, but I've hit a bit of a roadblock.

Working through the "Wire in data" section, my Storybook tests predictably stop working when `TaskList` is renamed to `PureTaskList` - however, the solution given still doesn't work. Instead, I'm just given the following error:

` Invariant Violation: Could not find "store" in the context of "Connect(PureTaskList)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(PureTaskList) in connect options.`

I've gone over all of my code and, as far as I can tell, it's identical to that shown in the article. I also had a look at the [linked commit](https://github.com/hichroma/learnstorybook-code/commit/dd04879) and noticed that `App.js` now wraps the `TaskList` component in a `Provider` with access to the store, which isn't mentioned in the article. Adding that leaves the app itself working correctly - does something similar need to happen in the component's story?

Cheers.

**Comment by tmeasday** [comment] 2019-01-30 23:45
Hi @jalovatt,

Is it possible you did `import PureTaskList from '..'` rather than `import { PureTaskList } from ...`?

**Comment by jonniebigodes** [comment] 2019-01-31 19:41
@jalovatt i was about to post a answer with a reproduction, but it looks like it's solved, Going to close this issue if you don't mind, Have a great time with Storybook 👍

**Closed by jonniebigodes** 2019-01-31 19:41 UTC
