### ISSUE TITLE
Angular tutorial runs fail

### ISSUE THREAD

**Issue by ParpaingVolant** [chromaui/learnstorybook.com#552] opened 2021-11-29 09:21 UTC
Hello there, 

First of all I'm deeply sorry if it is a newbie error or a duplicate. I'm following the [tutorial for Angular](https://storybook.js.org/tutorials/intro-to-storybook/angular/en/simple-component/) on Window10, working on VSCodium.

Running `npm run test` is getting me an error as following:
_jest --watchAll
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
npm ERR! errno 1
npm ERR! intro-storybook-angular-template@0.1.0 test: `jest --watchAll`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the intro-storybook-angular-template@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:_

And the log show the following:
_18 verbose node v12.15.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error intro-storybook-angular-template@0.1.0 test: `jest --watchAll`
22 error Exit status 1
23 error Failed at the intro-storybook-angular-template@0.1.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]_

Thank you for your time and stay safe !

**Comment by jonniebigodes** [comment] 2021-12-02 16:34
@ParpaingVolant thanks for reaching out to us with your issue, i'm going to take a look at it and run the tutorial on a Win 10 machine I have laying around. In the meantime could you provide some additional context on your node and npm versions?


Have a great day!

Stay safe

**Comment by jonniebigodes** [comment] 2022-02-13 16:17
Closing this as I was unable to reproduce. There's some interesting developments going on in the Storybook way of configuring Angular and an update to the tutorial is coming shortly. Once the documentation is up I'll circle back to this and check

**Closed by jonniebigodes** 2022-02-13 16:17 UTC
