### ISSUE TITLE
Fix prettier settings for MD files or reformat all of them

### ISSUE THREAD

**Issue by kylesuss** [chromaui/learnstorybook.com#162] opened 2019-10-07 15:07 UTC
It seems that saving a MD file causes it to update for those that have prettier enabled. I think that is expected, but maybe we can do 1 big PR where all of the files are reformatted at once so it doesn't just happen sporadically in smaller PRs.

**Comment by domyen** [comment] 2019-10-07 15:20
Yea I agree

**Comment by nickytonline** [comment] 2019-10-11 20:46
First, thanks for all the great work. I can work on this. I can also add a precommit hook via Husky and lint-staged if you want. I did it over on the DEV repository a while back.

https://github.com/thepracticaldev/dev.to/blob/master/package.json#L18

**Comment by domyen** [comment] 2019-10-11 21:14
@nickytonline I'm into it! What do you think @kylesuss?

**Comment by kylesuss** [comment] 2019-10-11 21:18
Sounds great @nickytonline 💯 

We had a little convo going in a PR that might be of interest to you:

https://github.com/chromaui/learnstorybook.com/pull/175#issuecomment-540718986

We aren't sure that the prettier/eslint setup is correct with regard to markdown files. It feels odd that the markdown files are autoformatting to have double quotes whereas our other files are single quoted. There are other inconsistencies as well.

Would be amazing if you could look into that while you do this 💪 

As for husky, I am all for it. We have that over in the Storybook design system as well.

**Comment by jonniebigodes** [comment] 2021-06-25 23:20
Closing this down as the issue is no longer present.

**Closed by jonniebigodes** 2021-06-25 23:20 UTC
Labels: enhancement
