### ISSUE TITLE
Intro To Storybook - Tests Fail after 'Single Component/Automated Testing' steps

### ISSUE THREAD

**Issue by jacknevitt** [chromaui/learnstorybook.com#236] opened 2019-12-23 12:21 UTC
Tests are expected to pass after pasting the code from the guide in the project.
The output on `yarn jest`:
```
yarn run v1.19.0
$ /Users/jnevitt/git/taskbox/node_modules/.bin/jest
 FAIL  src/storybook.test.js
  ● Test suite failed to run

    /Users/jnevitt/git/taskbox/src/storybook.test.js:2
    import initStoryshots from "@storybook/addon-storyshots";
           ^^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)

 FAIL  src/App.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: /Users/jnevitt/git/taskbox/src/App.test.js: Unexpected token (6:31)

      4 |
      5 | test('renders learn react link', () => {
    > 6 |   const { getByText } = render(<App />);
        |                                ^
      7 |   const linkElement = getByText(/learn react/i);
      8 |   expect(linkElement).toBeInTheDocument();
      9 | });

      at Parser.raise (node_modules/@babel/parser/lib/index.js:6975:17)
      at Parser.unexpected (node_modules/@babel/parser/lib/index.js:8368:16)
      at Parser.parseExprAtom (node_modules/@babel/parser/lib/index.js:9627:20)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/lib/index.js:9210:23)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/lib/index.js:9190:21)
      at Parser.parseExprOps (node_modules/@babel/parser/lib/index.js:9056:23)
      at Parser.parseMaybeConditional (node_modules/@babel/parser/lib/index.js:9029:23)
      at Parser.parseMaybeAssign (node_modules/@babel/parser/lib/index.js:8975:21)
      at Parser.parseExprListItem (node_modules/@babel/parser/lib/index.js:10297:18)
      at Parser.parseCallExpressionArguments (node_modules/@babel/parser/lib/index.js:9407:22)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        1.126s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jonniebigodes** [comment] 2019-12-23 19:16
@jacknevitt sorry for the issue you're experiencing. I think i have a solution for it.. Going to make some more tests and report back, do you mind waiting a bit longer?

**Comment by jacknevitt** [comment] 2019-12-23 22:26
Thanks! No problem. No need to rush, I'm just exploring storybook while things are quiet in the office

**Comment by jonniebigodes** [comment] 2019-12-23 22:59
@jacknevitt sorry to keep you waiting, but i've have a solution for your issue. 

The documentation is correct. I've just followed the steps to the end of the simple component section and everything checks out. Looking at your issue description, the issue is on your end. You mentioned that you issued `yarn jest` and the script that is setup by cra and is then used with Storybook is `yarn test`.

Running `yarn jest` you're basically invoking jest to run and you're not supplying any configuration and jest needs to be configured to properly run the test suit. That's why you're getting those errors.

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution

**Comment by renet** [comment] 2019-12-30 21:56
I'm having an issue in exactly the same place, so I post it here instead of opening a new issue:

I found that the following part of the `.storybook/config.js` file seems to be incorrect for the case of this tutorial:

```js
// .storybook/config.js

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

I followed the tutorial from scratch to verify my translation, and I found that according to the [storyshots docs](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core#configure-jest-to-work-with-webpacks-requirecontext) the above lines have to be replaced with the following, as we (or is it only me?) are using the CSF instead of `storiesOf` API:

```js
configure(req, module);
```

Without this change, Storybook didn't find any stories (after changing to the `require-context/macro` and thus the snapshot tests failed, as well. Is that true, or am I getting something wrong?

**Comment by jonniebigodes** [comment] 2019-12-30 23:06
@renet sorry for the inconvenience and misleading. The React version of the tutorial was updated so that it uses CSF format to allow early adoption by the readers. There are still some things that need to be addressed, one being that code snippet. The correct snippet should be the following:

```javascript
import { configure } from '@storybook/react';
import requireContext from 'require-context.macro';

import '../src/index.css';

configure(requireContext('../src/components', true, /\.stories\.js$/), module);
```
With this the snapshots will go through and stories will be picked up. 

Also the code base in which the tutorial relies is currently under review, The pr is still open.

If you don't mind, i would like for you to try the code i mentioned and provide feedback.

If you could update your translation with it it would be fantastic. 

Once again sorry for the inconvenience

**Comment by qasimalyas** [comment] 2020-01-05 00:21
I also just had this issue and using the updated code, specifically, the below resolved my issue. 

```javascript
configure(requireContext('../src/components', true, /\.stories\.js$/), module)
```

**Comment by jonniebigodes** [comment] 2020-01-13 21:07
@domyen and @jacknevitt if you both don't mind  i'm going to close this now as it's answered. 

@jacknevitt If you have further questions, re-open it and leave a comment or try the Discord chat or the Storybook issue tracker. Thanks!

**Closed by jonniebigodes** 2020-01-13 21:07 UTC
