### ISSUE TITLE
Syntax error in the documentation

### ISSUE THREAD

**Issue by lucapu88** [chromaui/learnstorybook.com#480] opened 2021-04-22 10:50 UTC
![Schermata da 2021-04-22 10-37-30](https://user-images.githubusercontent.com/56302007/115702525-57829000-a369-11eb-9050-077b45b43bdc.png)

In your documentation there is an extra brace that gives an error in compilation, and for an inexperienced user, doing a copy and paste, could create problems......

**Comment by jonniebigodes** [comment] 2021-04-23 21:52
@lucapu88 thanks for bringing this to our attention. I'm currently updating the tutorial for 6.2 and this issue is already covered. A pull request will be up early next week to address this.

Stay safe

**Comment by jonniebigodes** [comment] 2021-04-27 19:17
@lucapu88 the pull request that I've mentioned in my earlier comment. If you don't mind I'm going to close this issue as the problem is fixed with the mentioned pull request.

Please feel free to open a new issue if you encounter a problem with the tutorials.

Stay safe

**Closed by jonniebigodes** 2021-04-27 19:17 UTC
